config/routes.rb
Rails.application.routes.draw do
  get  '/signup',  to: 'users#new'
  root :to => "sessions#new"
  get 'sessions/new'
  get 'friendships/create'
  get '/search', to: 'users#search'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friend_sent, class_name: 'Friendship',
                          foreign_key: 'sent_by_id',
                          inverse_of: 'sent_by',
                          dependent: :destroy
  has_many :friend_request, class_name: 'Friendship',
                        foreign_key: 'sent_to_id',
                        inverse_of: 'sent_to',
                        dependent: :destroy
  has_many :friends, -> { merge(Friendship.friends) },
            through: :friend_sent, source: :sent_to
  has_many :pending_requests, -> { merge(Friendship.not_friends) },
            through: :friend_sent, source: :sent_to
  has_many :received_requests, -> { merge(Friendship.not_friends) },
            through: :friend_request, source: :sent_by

  validates :name, presence: true
  validates :website, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        reset_session
        log_in @user
        scrape_site(@user, @user.website)
        short_url(@user, @user.website)
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].blank?
      redirect_to users_path and return
    else
      @parameter = params[:search].downcase
      @results = User.all.where("array_to_string(headings, '||') ILIKE :name", name: "%#{@parameter}%")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :website)
    end
end

app/helpers/users_helper.rb
require 'nokogiri'
require 'open-uri'

module UsersHelper

  def scrape_site(user, the_url)
    html = URI.open(the_url)
    doc = Nokogiri::HTML(html)

    headings = doc.css('h1', 'h2', 'h3')
    heading_arr = []

    headings.each do |h|
      hedVal = h.text
      heading_arr << hedVal

      user.update headings: heading_arr
    end
  end

  def short_url(user, url)
    token ='8f1a0d4a1aeb4a109b4ca3c23ad95a9bee0009c8'
    client = Bitly::API::Client.new(token: token)
    bitlink = client.shorten(long_url: url)
    user.update shortened: bitlink.link
  end

  def mutual_friends(user)
    user.friends
  end

  def friend_request_sent?(user)
    current_user.friend_sent.exists?(sent_to_id: user.id, status: false)
  end

  # Checks whether or not a user has sent a friend request to the current user
  # returning either true or false
  def friend_request_recieved?(user)
    current_user.friend_request.exists?(sent_by_id: user.id, status: false)
  end

  # Checks whether or not a user has had a friend request sent to them by the current user
  # or if the current user has been sent a friend request by the user
  # returning either true or false
  def possible_friend?(user)
    request_sent = current_user.friend_sent.exists?(sent_to_id: user.id)
    request_recieved = current_user.friend_request.exists?(sent_by_id: user.id)

    return true if request_sent != request_recieved
    return true if request_sent == request_recieved && request_sent == true
    return false if request_sent == request_recieved && request_sent == false
  end

  def friends_already(user)
    Friendship.find_by(sent_by_id: current_user.id, sent_to_id: user.id, status: true) || 
    Friendship.find_by(sent_by_id: user.id, sent_to_id: current_user.id, status: true)
  end

  def me?(user)
    user == current_user
  end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, placeholder: 'https://www.webaddress.com', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create account', class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="heading">Experts</h1>

<table class="table table-striped table-dark">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Short URL</th>
      <th scope="col">No. of friends</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="bg-warning">
        <td><%=link_to user.name, user %></td>
        <td><a href="<%= user.shortened %>"><%= user.shortened %></a></td>
        <td><%= user.friends.count %></td>
        <td><%= link_to 'Show', user, class: "btn btn-warning" %></td>

        <td>
          <% if friend_request_sent?(user) %>
            <p>Waiting for approval</p>
            <% elsif friend_request_received?(user) %>
              <div>
              <%= link_to 'Accept Request', accept_friend_user_friendships_path({:user_id => user.id}), class: "btn btn-success"%> 
              <%= link_to 'Cancel Request', decline_friend_user_friendships_path({:user_id => user.id}), class: "btn btn-danger"%> 
            </div>
            <% elsif friends_already(user) %>
            <p>friends already</p>
            <% elsif me?(user)%>
            <%= link_to 'go to my profile', current_user%>
            <% else %>
            <%= link_to 'Add friend', friendships_create_path({:sent_to_id => user.id, :status => false}), class: "btn btn-success" %>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back to Login', logout_path, method: :delete%>

app/views/users/search.html.erb
<h3>Users who write about: <%= @parameter %></h3>

<% @results.each do |result| %>
  <% if !current_user.friends.include?(result) %>
    <p>
      <%= link_to result.name, result %> get introduced by your friend(s): <% mutual_friends(result).each do |r|%>
        <% if current_user.friends.include?(r) %>
          <%= link_to r.name, r %>
        <% end %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag(search_path, :method => "get") do %>
<div class="form-inline">
  <%= search_field_tag :search, params[:search], placeholder: "Enter search text", class: 'form-control' %>
 
  <%= button_tag 'Search', :headings => nil, class: "btn btn-primary buton" %>
</div>
<% end %>


<div class="row diver">
  <div class="col-lg-4">
    <strong>Name:</strong>
    <%= @user.name %>
  </div>

  <div class="col-lg-4">
    <strong>Website:</strong>
    <a href="<%= @user.website %>"><%= @user.website %></a>
  </div>

  <div class="col-lg-4">
    <strong>Shortened url:</strong>
    <a href="<%= @user.shortened %>"><%= @user.shortened %></a>
  </div>
</div>

<div class="diver">
  <div class="row">
  <div class="col-lg-6 pt-4">
    <h4><strong>Headings from website:</strong></h4>
    <% @user.headings.each do |h| %>
      <li><%= h %></li>
    <% end %>
  </div>

  <div class="col-lg-6">
    <h4><strong>Friends:</strong></h4>
    <% @user.friends.each do |f| %>
    <li>
    <%= f.name %>
    <%= link_to 'View profile', f %>
    </li>
    <% end %>
  </div>
  </div>
</div>
<div class="links">
<%= link_to 'Edit profile', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Logout', logout_path, method: :delete %>
</div>